### ISSUE TITLE
TimeoutError not available in older python versions

### ISSUE THREAD

**Issue by ijnek** [ros-sports/game_controller_spl#41]
For the ``foxy``and ``galactic`` branch with an older python version, ``except socket.timeout:`` should be used instead of ``except TimeoutError:`` at https://github.com/ros-sports/gc_spl/blob/aa642e63f051a328d48724bf315b1ed6a2d7b367/gc_spl_2022/gc_spl_2022/gc_spl.py#L83 and
https://github.com/ros-sports/gc_spl/blob/aa642e63f051a328d48724bf315b1ed6a2d7b367/gc_spl_2022/test/test_gc_spl.py#L151

Otherwise, the exception isn't caught, and the following prints:

```sh
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/ros/foxy/lib/python3.8/site-packages/gc_spl_2022/gc_spl.py", line 75, in _loop
    data, (self._host, _) = self._client.recvfrom(1024)
socket.timeout: timed out
```

**Comment by ijnek** [comment]
Resolved in #42
